"""
TYRETRACE — Twin Engine Output Schemas
Defines the output contracts generated by the Physics Digital Twin.
Every output clearly reports signal provenance: MEASURED, DERIVED, MODELLED, or UNAVAILABLE.
"""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class SignalOrigin(str, Enum):
    MEASURED = "MEASURED"
    DERIVED = "DERIVED"
    MODELLED = "MODELLED"
    UNAVAILABLE = "UNAVAILABLE"


class TwinEngineOutput(BaseModel):
    """
    Authoritative Digital Twin State Output for a single telemetry time-step.
    Contains both the first-principles expected physical state and the explicit
    provenance audit for all input channels.
    """

    timestamp: float = Field(..., description="Timestamp of the evaluated telemetry frame in seconds")
    session_id: str = Field(..., description="Session identifier")
    lap: int = Field(..., description="Lap index")

    # Core Expected Physics Signals (SI Units)
    expected_acceleration_mps2: float = Field(
        ..., description="Expected vehicle longitudinal acceleration: (F_traction - F_drag - F_rolling - F_brake) / m [m/s^2]"
    )
    expected_drag_n: float = Field(
        ..., description="Aerodynamic drag force: 0.5 * rho * Cd * A * v^2 [N]"
    )
    expected_rolling_resistance_n: float = Field(
        ..., description="Rolling resistance force: Crr * m * g [N]"
    )
    expected_brake_force_n: float = Field(
        ..., description="Modelled four-wheel braking force from driver pedal effort [N]"
    )
    expected_traction_force_n: float = Field(
        ..., description="Modelled longitudinal drive traction force from throttle & engine power limit [N]"
    )
    expected_vertical_load_n: float = Field(
        ..., description="Total vehicle normal load: m * g + F_aero [N]"
    )

    # Expected Corner Normal Loads (SI Units)
    expected_fz_front_n: float = Field(..., description="Expected total front axle vertical load [N]")
    expected_fz_rear_n: float = Field(..., description="Expected total rear axle vertical load [N]")
    expected_load_transfer_n: float = Field(..., description="Longitudinal load transfer magnitude: m * |ax| * h / L [N]")

    # Kinematic & Derived Comparison Channels
    actual_speed_mps: float = Field(..., description="Measured vehicle ground speed [m/s]")
    derived_acceleration_mps2: Optional[float] = Field(
        None, description="Longitudinal acceleration derived from consecutive speed deltas: Delta v / Delta t [m/s^2]"
    )

    # Thermal Model Outputs
    thermal_status: str = Field("UNAVAILABLE", description="Thermal model calculation status (CALCULATED or UNAVAILABLE)")
    thermal_prediction_k_per_s: Optional[float] = Field(
        None, description="Tyre temperature derivative dT/dt [K/s], or None if inputs unavailable"
    )

    # Confidence and Provenance Audit
    model_confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Overall digital twin model confidence score [0.0 - 1.0]"
    )
    measured_inputs: Dict[str, Any] = Field(
        default_factory=dict, description="Fields directly measured from vehicle/sensor telemetry"
    )
    derived_inputs: Dict[str, Any] = Field(
        default_factory=dict, description="Fields derived mathematically from measured signals (e.g. Delta v / Delta t)"
    )
    modelled_inputs: Dict[str, Any] = Field(
        default_factory=dict, description="Physics parameter assumptions and nominal models"
    )
    unavailable_inputs: List[str] = Field(
        default_factory=list, description="Sensor channels not provided by the telemetry source (strictly None)"
    )
    assumptions: List[str] = Field(
        default_factory=list, description="Human-readable list of engineering assumptions applied in this evaluation"
    )
